site_name: RPG Notes
repo_url: https://github.com/billbrod/rpg_notes

theme:
  name: 'material'
  custom_dir: overrides
  palette:
    primary: 'indigo'
    features:
      - navigation.tabs
plugins:
    - search
    - literate-nav:
          nav_file: docs/SUMMARY.md     # navigation file for literate navigation
    - section-index                    # plugin for creating section index

extra_javascript:
  - https://identity.netlify.com/v1/netlify-identity-widget.js

nav:
    - Home: index.md
    - DM Notes: dm.md
